# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

"""Hermetic Android SDK + Temurin 17 for React Native Gradle (Android only, Linux x86_64)."""

# Temurin 17.0.13+11 (Linux x64) — https://adoptium.net/
_JDK_URL = "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.13%2B11/OpenJDK17U-jdk_x64_linux_hotspot_17.0.13_11.tar.gz"
_JDK_SHA256 = "8682892fc02965930b9022c066fa164dd6f458ef4a5dc262016aa28333b30f49"
_JDK_STRIP_PREFIX = "jdk-17.0.13+11"

# Android cmdline-tools — https://developer.android.com/studio#command-line-tools-only
_CMDLINE_URL = "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
_CMDLINE_SHA256 = "2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258"

def _rn_android_sdk_repository_impl(rctx):
    if rctx.os.name != "linux":
        fail("rn_android_sdk: hermetic fetch is implemented for Linux only (found os.name=%r). " % (rctx.os.name,) +
             "iOS is intentionally out of scope. On macOS, build with Docker (src/react-native-app/android.Dockerfile) " +
             "or install Android Studio’s SDK and do not depend on @rn_android_sdk.")
    if rctx.os.arch != "amd64":
        fail("rn_android_sdk: hermetic fetch is implemented for linux-amd64 only (found arch=%r). " % (rctx.os.arch,) +
             "Extend tools/bazel/rn_android/sdk_repo.bzl with aarch64 URLs if you need ARM Linux.")

    rctx.report_progress("Downloading Temurin 17 JDK")
    rctx.download_and_extract(
        url = _JDK_URL,
        sha256 = _JDK_SHA256,
        stripPrefix = _JDK_STRIP_PREFIX,
        output = "jdk",
    )

    rctx.report_progress("Downloading Android command-line tools")
    rctx.download_and_extract(
        url = _CMDLINE_URL,
        sha256 = _CMDLINE_SHA256,
        output = "ct_zip",
    )

    # Zip root is cmdline-tools/ — install as $SDK/cmdline-tools/latest (required layout).
    rctx.execute(["mkdir", "-p", "sdk/cmdline-tools"], quiet = False)
    mv = rctx.execute(["mv", "ct_zip/cmdline-tools", "sdk/cmdline-tools/latest"], quiet = False)
    if mv.return_code != 0:
        fail("rn_android_sdk: could not move cmdline-tools: " + (mv.stderr or mv.stdout))

    java_home = str(rctx.path("jdk"))
    sdk_root = str(rctx.path("sdk"))
    sm = "%s/cmdline-tools/latest/bin/sdkmanager" % sdk_root
    env = {
        "JAVA_HOME": java_home,
        "PATH": "%s/bin:/usr/bin:/bin" % java_home,
    }

    rctx.report_progress("sdkmanager --licenses (may take a minute)")
    lic = rctx.execute(
        ["/bin/bash", "-c", "yes | \"%s\" --sdk_root=\"%s\" --licenses" % (sm, sdk_root)],
        environment = env,
        timeout = 600,
    )
    if lic.return_code != 0:
        fail("rn_android_sdk: sdkmanager --licenses failed: " + (lic.stderr or lic.stdout))

    # Match src/react-native-app/android/build.gradle (compileSdk 34, build-tools 34.0.0, NDK 26.1.10909125).
    pkgs = ["platform-tools", "platforms;android-34", "build-tools;34.0.0", "ndk;26.1.10909125"]
    quoted = " ".join(['"%s"' % p for p in pkgs])
    rctx.report_progress("sdkmanager install (large download; first run can take 10–20+ minutes)")
    ins = rctx.execute(
        ["/bin/bash", "-c", "\"%s\" --sdk_root=\"%s\" %s" % (sm, sdk_root, quoted)],
        environment = env,
        timeout = 3600,
    )
    if ins.return_code != 0:
        fail("rn_android_sdk: sdkmanager install failed: " + (ins.stderr or ins.stdout))

    rctx.file(
        "BUILD.bazel",
        """# Generated by rn_android_sdk_repository — do not edit.
package(default_visibility = ["//visibility:public"])

exports_files(["root"])
""",
    )
    rctx.file("root", "")

rn_android_sdk_repository = repository_rule(
    implementation = _rn_android_sdk_repository_impl,
    doc = "Downloads Temurin 17 + Android SDK packages (API 34, build-tools 34.0.0, NDK 26.1.10909125). Linux x86_64 only.",
)
